<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Plugin version
 * @package    local_invoice
 * @copyright  2026 eLearn Solutions
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
 
// /local/invoice/lang/en/local_invoice.php

defined('MOODLE_INTERNAL') || die();

$string['pluginname'] = 'Invoice Generator';

$string['license_key'] = 'Pro License Key';
$string['license_key_desc'] = "Enter your Invoice Pro license key here. Use the code 'free' if you don't have a license key.";
$string['free_version_notice'] = "You are using the free version. Enter a valid license key to unlock all features.";
$string['pro_license_required'] = 'You must enter and validate a valid Pro License Key before editing these settings.';
$string['invalid_license'] = 'Invalid license key. Please check and try again.';

$string['license_server_error'] = 'Could not validate license key (licensing server unavailable). Please try again.';

$string['pro_license_status'] = 'Pro license status';
$string['pro_license_valid_until'] = 'Pro license valid until: {$a}';
$string['pro_license_expired'] = 'Pro license has expired';
$string['pro_license_free'] = 'Pro license: Free mode';

// Billing details (end-user form).
$string['billing_heading'] = 'Billing details';
$string['billing_company'] = 'Company / billing name';
$string['billing_vatnumber'] = 'Tax / VAT number';
$string['billing_address'] = 'Address';
$string['billing_city'] = 'City';
$string['billing_province'] = 'Province';
$string['billing_postalcode'] = 'Postal code';
$string['billing_intro_note'] = 'Please provide your billing details. We will use this to generate your invoices.';
$string['billing_regenerate_note'] = 'If you update your billing details and you want the change to reflect on invoices, delete the existing invoice PDF(s) from your Private files and generate them again.';

// No-invoice page.
$string['noinvoice_title'] = 'No invoice available';
$string['noinvoice_text'] = 'You have no course purchases via PayPal or PayFast.';

// Privacy API.
$string['privacy:metadata:local_invoice'] = 'Invoice records generated by the plugin.';
$string['privacy:metadata:local_invoice:userid'] = 'The ID of the user the invoice belongs to.';
$string['privacy:metadata:local_invoice:enrolid'] = 'The enrolment instance ID used to generate the invoice.';
$string['privacy:metadata:local_invoice:courseid'] = 'The course ID the invoice relates to.';
$string['privacy:metadata:local_invoice:amount'] = 'The enrolment amount stored on the invoice record.';
$string['privacy:metadata:local_invoice:currency'] = 'The currency stored on the invoice record.';
$string['privacy:metadata:local_invoice:invoice_no'] = 'The invoice number.';
$string['privacy:metadata:local_invoice:invoice_date'] = 'The invoice date.';
$string['privacy:metadata:local_invoice:timecreated'] = 'When the invoice record was created.';
$string['privacy:metadata:local_invoice:timemodified'] = 'When the invoice record was last modified.';

$string['privacy:metadata:local_invoice_user'] = 'Billing details captured from the user for invoice generation.';
$string['privacy:metadata:local_invoice_user:userid'] = 'The ID of the user these billing details belong to.';
$string['privacy:metadata:local_invoice_user:company'] = 'Company / billing name.';
$string['privacy:metadata:local_invoice_user:vatnumber'] = 'Tax / VAT number.';
$string['privacy:metadata:local_invoice_user:address'] = 'Address.';
$string['privacy:metadata:local_invoice_user:city'] = 'City.';
$string['privacy:metadata:local_invoice_user:province'] = 'Province.';
$string['privacy:metadata:local_invoice_user:postalcode'] = 'Postal code.';
$string['privacy:metadata:local_invoice_user:timecreated'] = 'When the billing record was created.';
$string['privacy:metadata:local_invoice_user:timemodified'] = 'When the billing record was last modified.';

$string['privacy:metadata:license_server'] = 'The plugin can contact an external licensing server to validate and activate Pro license keys.';
$string['privacy:metadata:license_server:license_key'] = 'The Pro license key entered by the site administrator.';
$string['privacy:metadata:license_server:siteurl'] = 'The site URL, sent to associate the license key with this Moodle site.';

$string['companylogo'] = 'Company Logo';
$string['companylogo_desc'] = 'Upload the company logo for invoices (recommended size: 250x100px, PNG/JPG)';

$string['companyname'] = 'Company Name';
$string['companyname_desc'] = 'Company name as it will appear on invoices';

$string['address'] = 'Address';
$string['address_desc'] = 'Company street address';

$string['city'] = 'City';
$string['city_desc'] = 'Company city';

$string['postalcode'] = 'Postal Code';
$string['postalcode_desc'] = 'Company postal code';

$string['taxnumber'] = 'Tax Number';
$string['taxnumber_desc'] = 'Company TAX/VAT number';

$string['invoiceprefix'] = 'Invoice Prefix';
$string['invoiceprefix_desc'] = 'Enter a prefix for all invoice numbers, e.g. INV- or 2025-, etc. Leave blank for no prefix.';

$string['invoicestart'] = 'Invoice Starting Number';
$string['invoicestart_desc'] = 'The first invoice number to use (default: 900001).';

$string['taxsettings_heading'] = 'Tax settings';
$string['taxsettings_desc'] = 'Control whether tax/VAT is shown as a breakdown on the PDF.';

$string['showtaxbreakdown'] = 'Show tax/VAT breakdown';
$string['showtaxbreakdown_desc'] = 'If enabled, the invoice will show subtotal, tax/VAT, and total. If disabled, only the total amount is shown.';

$string['taxpercent'] = 'Tax/VAT percentage';
$string['taxpercent_desc'] = 'Percentage used for tax/VAT breakdown calculations (e.g. 15 for 15%). Only used when tax/VAT breakdown is enabled.';

$string['profeatures_heading'] = 'Upgrade to Pro';
$string['profeatures_desc'] = '
<ul>
    <li>Add a <strong>company logo</strong> to your invoice</li>
    <li>Add a <strong>tax number</strong> field</li>
    <li>Show a <strong>tax/VAT breakdown</strong> on your invoices</li>
    <li>Remove the <strong>"Plugin provided by eLearn Solutions" watermark image</strong> from generated invoices</li>
</ul>
<p>Visit our Online Shop at <a href="https://shop.elearnsolutions.co.za">shop.elearnsolutions.co.za</a> to purchase a Pro key and to unlock these features.</p>';